name: flutter_raycasting
description: A Raycasting Engine for Flutter, based on https://github.com/vinibiavatti1/raycastingtutorial.

publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  image: ^4.0.17
  statsfl: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
